conditioning:
  method: ps
  params:
    scale: 0.8

data:
  name: imagenet256
  root: ./data/imagenet256/

measurement:
  operator:
    name: elic
    q: 3

  noise: 
    name: gaussian
    sigma: 0.05

save_path: ./elic0016_DCVC_0_quality_result_v1.json