conditioning:
  method: ps
  params:
    scale: 0.8

data:
  name: ffhq
  root: ./data/foreman_cif/

measurement:
  operator:
    name: DCVC
    q: 4

  noise: 
    name: gaussian
    sigma: 0.05

save_path: ./elic0150_DCVC_2_quality_result_v1.json