conditioning:
  method: ps
  params:
    scale: 0.5
    noise_step: 1000

data:
  name: ffhq
  root: ./data/test1/

measurement:
  operator:
    name: gg18_test
    q: 2

  noise: 
    name: gaussian
    sigma: 0.05

save_path: ./ddim_test.json